import { motion, useMotionTemplate, useMotionValue } from 'framer-motion';
import { ArrowUpRight, Code2, Fingerprint, Globe2, Terminal, Trophy } from 'lucide-react';
import type { ReactNode } from 'react';
/** Reusable spotlight surface: pointer movement updates motion values without React renders. */
export function SpotlightCard({ children, className = '' }: { children: ReactNode; className?: string }) {
 const x=useMotionValue(-500),y=useMotionValue(-500);
 const background=useMotionTemplate`radial-gradient(400px circle at ${x}px ${y}px,rgba(198,245,120,.10),transparent 75%)`;
 return <motion.article className={`bento-card ${className}`} whileHover={{y:-4}} transition={{type:'spring',stiffness:220,damping:25}} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set(e.clientX-r.left);y.set(e.clientY-r.top);}} onPointerLeave={()=>{x.set(-500);y.set(-500);}}><motion.div className="card-spotlight" style={{background}}/>{children}</motion.article>;
}
const stack=['TypeScript','React 19','Python','Java','Node.js','Docker','AWS','MongoDB','GSAP','Kubernetes','Linux','MySQL'];
export function BentoGrid(){return <section id="about" className="section-shell section-pad"><div className="section-heading"><span className="eyebrow">01 / THE PERSON BEHIND THE CODE</span><h2>Curiosity is the constant.<br/><span>Building is how I think.</span></h2></div><div className="bento-grid"><SpotlightCard className="about-card"><Fingerprint size={30} strokeWidth={1}/><div><h3>Engineer. Researcher.<br/>People person.</h3><p>I’m Lungsom, a Computer Science & Engineering student turning complex problems into useful software. From applied R&D to developer communities, I connect technical depth with a shared sense of possibility.</p></div><span className="mono card-foot">CURRENTLY EXPLORING / WHAT COMES NEXT <ArrowUpRight size={16}/></span></SpotlightCard><SpotlightCard className="grant-card"><div className="card-label"><Globe2 size={19}/><span className="mono">RESEARCH → REALITY</span></div><div className="stat">₹5<span>L</span></div><h3>Ideas worth backing.</h3><p>Research grant procured while leading applied R&D at Vernovate.</p><div className="badge">CHIEF TECHNICAL OFFICER</div></SpotlightCard><SpotlightCard className="algo-card"><div className="card-label"><Code2 size={20}/><span className="mono">ALGORITHMIC CORE</span></div><div className="stat">200<span>+</span></div><h3>Problems. Possibilities.</h3><p>LeetCode problems solved.<br/>A daily practice in clearer thinking.</p><div className="activity-grid" aria-hidden="true">{Array.from({length:65},(_,i)=><span key={i} style={{opacity:[.1,.3,.5,.85,.2][(i*7)%5]}}/>)}</div><small>Profile snapshot · provided milestone</small></SpotlightCard><SpotlightCard className="community-card"><div><div className="card-label"><Trophy size={21}/><span className="mono">BUILDING TOGETHER</span></div><h3>Good technology.<br/>Great company.</h3><p>Technical Lead, GDGoC AdtU.<br/>Bringing developers together through HackStone, workshops and cloud bootcamps.</p></div><div className="community-symbol" aria-hidden="true">&lt;<span>/</span>&gt;</div></SpotlightCard><SpotlightCard className="stack-card"><div className="card-label"><Terminal size={20}/><span className="mono">MY WORKING TOOLKIT</span></div><div className="stack-tags">{stack.map((s,i)=><motion.span key={s} whileHover={{y:-5,rotate:i%2?3:-3,scale:1.06}} transition={{type:'spring',stiffness:350,damping:15}}>{s}</motion.span>)}</div><p>Different tools. The same attention to detail.</p></SpotlightCard></div></section>}
