import { motion, useMotionValue, useSpring, useMotionTemplate, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, GitBranch, Network, FileText, Check, LockKeyhole } from 'lucide-react';
export type Project = { id:string; name:string; category:string; description:string; tags:string[]; detail:string; source?:string; };
export function ProjectCard({ project, onOpen }: {project:Project; onOpen:(p:Project)=>void}){
 const rawX=useMotionValue(0),rawY=useMotionValue(0),glareX=useMotionValue(50),glareY=useMotionValue(50);
 const rotateX=useSpring(rawX,{stiffness:180,damping:24}),rotateY=useSpring(rawY,{stiffness:180,damping:24});
 const glare=useMotionTemplate`radial-gradient(circle at ${glareX}% ${glareY}%,#ffffff17,transparent 60%)`;
 const reduced=useReducedMotion();
 return <div className="project-perspective"><motion.article className={`project-card project-${project.id}`} style={{rotateX,rotateY,transformStyle:'preserve-3d'}} onPointerMove={e=>{if(reduced||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();const x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;rawX.set((.5-y)*7);rawY.set((x-.5)*7);glareX.set(x*100);glareY.set(y*100);}} onPointerLeave={()=>{rawX.set(0);rawY.set(0)}}><motion.div className="project-glare" style={{background:glare}}/><div className="project-visual"><span className="mockup-label mono">{project.id==='resume'?'PRODUCT INTERFACE STUDY':'SYSTEM ARCHITECTURE STUDY'}</span>{project.id==='resume'?<div className="resume-window"><div className="window-bar"><span><FileText size={12}/> ResumeForge</span><span className="mono">LOCAL / PRIVATE <LockKeyhole size={10}/></span></div><div className="resume-body"><aside><b>Your next chapter.</b><span className="selected">01 Personal information</span><span>02 Experience</span><span>03 Education</span><span>04 Skills</span><div className="mock-button">Export PDF ↗</div></aside><div className="paper"><b>ALEX MORGAN</b><span>SOFTWARE ENGINEER</span><hr/><strong>PROFILE</strong><div className="paper-lines"/><strong>EXPERIENCE</strong><div className="paper-lines"/><strong>EDUCATION</strong><div className="paper-lines short"/></div></div></div>:<div className="traffic-diagram"><div className="traffic-node top"><Network size={21}/><span>ROAD NETWORK</span></div><div className="flow-line"/><div className="traffic-pair"><div className="traffic-node">GNN<span>Spatial understanding</span></div><div className="traffic-node">PPO<span>Adaptive decisions</span></div></div><div className="flow-line"/><div className="traffic-node bottom"><i className="status-dot"/> SIGNAL OPTIMIZATION</div><div className="diagram-coordinates mono">OBSERVE → LEARN → ADAPT</div></div>}</div><div className="project-info"><div className="project-category mono">{project.category}<span>0{project.id==='resume'?'1':'2'} / 02</span></div><button className="project-title" onClick={()=>onOpen(project)} data-cursor="View"><h3>{project.name}</h3><span className="circle-arrow"><ArrowUpRight size={22}/></span></button><p>{project.description}</p><div className="project-tags">{project.tags.map(t=><span key={t}>{t}</span>)}</div><div className="project-footer"><span>{project.id==='resume'?<><Check size={14}/> 100% client-side & private</>:<><GitBranch size={14}/> Applied reinforcement learning</>}</span><button onClick={()=>onOpen(project)}>Explore project ↗</button></div></div></motion.article></div>
}
