import { useEffect, useRef, useState } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { X, ArrowUpRight } from 'lucide-react';
import { ProjectCard, type Project } from './ProjectCard';
const projects:Project[]=[{id:'resume',name:'ResumeForge',category:'OPEN SOURCE / PRODUCT ENGINEERING',description:'Your story, beautifully structured. A private resume builder that keeps every detail in your browser.',tags:['React 19','Vite','Client-side'],detail:'A production open-source resume builder engineered with React 19 and Vite. Its client-side architecture keeps resume information in the browser, prioritizing privacy while making document creation approachable.'},{id:'traffic',name:'Intelligent Traffic System',category:'APPLIED AI / URBAN SYSTEMS',description:'Rethinking the flow of a city. Adaptive traffic optimization that learns from connected road networks.',tags:['Graph Neural Networks','PPO','Google Maps API'],detail:'The Intelligent Traffic Management System combines Graph Neural Networks for road-network relationships with Proximal Policy Optimization reinforcement learning for autonomous transit optimization, integrated with the Google Maps API.'}];
export function Projects(){const section=useRef<HTMLElement>(null),track=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null);const [selected,setSelected]=useState<Project|null>(null);
 useEffect(()=>{const mm=gsap.matchMedia();mm.add('(min-width: 1000px) and (prefers-reduced-motion: no-preference)',()=>{if(!track.current||!section.current)return;const distance=()=>Math.max(0,track.current!.scrollWidth-section.current!.clientWidth+window.innerWidth*.14);gsap.to(track.current,{x:()=>-distance(),ease:'none',scrollTrigger:{trigger:section.current,start:'top top',end:()=>`+=${distance()+400}`,pin:true,scrub:1,invalidateOnRefresh:true}})});return()=>mm.revert()},[]);
 const open=(p:Project)=>{setSelected(p);dialog.current?.showModal()};
 return <><section id="work" ref={section} className="projects-section section-pad"><div className="section-heading section-shell"><div className="heading-row"><span className="eyebrow">02 / SELECTED WORK</span><span className="mono muted">A FEW THINGS I’VE PUT INTO THE WORLD</span></div><h2>Built with intent.<br/><span>Engineered for impact.</span></h2></div><div ref={track} className="project-track">{projects.map(p=><ProjectCard key={p.id} project={p} onOpen={open}/>)}</div><div className="project-scroll-note mono">SCROLL TO EXPLORE <span>━━━━━━━━━</span> 01 — 02</div></section><dialog ref={dialog} className="project-dialog" onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close()}}><button className="dialog-close" onClick={()=>dialog.current?.close()} aria-label="Close project"><X/></button>{selected&&<><span className="eyebrow">{selected.category}</span><h2>{selected.name}</h2><p>{selected.detail}</p><div className="project-tags">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><div className="detail-note">The interface above is an illustrative study. Repository URLs and verified live metrics can be connected when supplied.</div><a href="#contact" className="text-link" onClick={()=>dialog.current?.close()}>Discuss this project <ArrowUpRight size={18}/></a></>}</dialog></>}
