import { Component, Suspense, useRef, useState, type ReactNode } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Float } from '@react-three/drei';
import { useReducedMotion } from 'framer-motion';
import type { Group } from 'three';
function Pop({children,ready,reduced,order}:{children:ReactNode;ready:boolean;reduced:boolean;order:number}){const ref=useRef<Group>(null);const elapsed=useRef(0);useFrame((_,delta)=>{if(!ref.current)return;if(!ready){elapsed.current=0;ref.current.scale.setScalar(0);return}elapsed.current+=delta;const t=Math.min(1,Math.max(0,(elapsed.current-.45-order*.22)/.75));const scale=reduced?1:1+2.70158*Math.pow(t-1,3)+1.70158*Math.pow(t-1,2);ref.current.scale.setScalar(Math.max(0,scale))});return <group ref={ref} scale={reduced?1:0}>{children}</group>}
function Turn({children,turn,reduced,position}:{children:ReactNode;turn:number;reduced:boolean;position:[number,number,number]}){const ref=useRef<Group>(null);useFrame((_,delta)=>{if(!ref.current)return;const target=turn*Math.PI*2;const k=reduced?1:1-Math.exp(-delta*7);ref.current.rotation.y+=(target-ref.current.rotation.y)*k;ref.current.rotation.z+=(turn*.35-ref.current.rotation.z)*k});return <group ref={ref} position={position}>{children}</group>}
function Shapes({reduced,ready,turns}:{reduced:boolean;ready:boolean;turns:number[]}){const group=useRef<Group>(null);const {viewport}=useThree();const x=viewport.width*.34,y=viewport.height*.27;const size=viewport.width<7?.42:.68;useFrame(({pointer},delta)=>{if(!group.current||reduced)return;const k=1-Math.exp(-delta*2);group.current.rotation.y+=(pointer.x*.1-group.current.rotation.y)*k;group.current.rotation.x+=(-pointer.y*.08-group.current.rotation.x)*k});return <group ref={group}><Float speed={reduced?0:1.1} rotationIntensity={reduced?0:.25} floatIntensity={reduced?0:.25}><Pop ready={ready} reduced={reduced} order={0}><Turn turn={turns[0]} reduced={reduced} position={[-x,y,0]}><mesh rotation={[.3,.1,-.5]} scale={size}><coneGeometry args={[.72,1.4,3]}/><meshStandardMaterial color={["#ff920e","#9c43ed","#ffbf00","#00bfa2"][turns[0]%4]} roughness={.7} flatShading/></mesh></Turn></Pop><Pop ready={ready} reduced={reduced} order={1}><Turn turn={turns[1]} reduced={reduced} position={[x,y,-.5]}><mesh rotation={[.6,.5,.3]} scale={size*.8}><octahedronGeometry args={[.85,0]}/><meshStandardMaterial color={["#13b8c4","#9c43ed","#ffbf00","#00bfa2"][turns[1]%4]} roughness={.6} flatShading/></mesh></Turn></Pop><Pop ready={ready} reduced={reduced} order={2}><Turn turn={turns[2]} reduced={reduced} position={[-x,-y,0]}><mesh rotation={[.15,0,-.35]} scale={size}><cylinderGeometry args={[.58,.58,1.2,16]}/><meshStandardMaterial color={["#2464f2","#9c43ed","#ffbf00","#00bfa2"][turns[2]%4]} roughness={.6}/></mesh></Turn></Pop><Pop ready={ready} reduced={reduced} order={3}><Turn turn={turns[3]} reduced={reduced} position={[x,-y,0]}><mesh rotation={[.5,.4,.25]} scale={size}><boxGeometry args={[1,1,1]}/><meshStandardMaterial color={["#f00e29","#9c43ed","#ffbf00","#00bfa2"][turns[3]%4]} roughness={.6} flatShading/></mesh></Turn></Pop></Float></group>}
class Boundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?null:this.props.children}}
export default function SpatialScene({index:_index,ready=true}:{index:number;ready?:boolean}){const reduced=!!useReducedMotion();const [turns,setTurns]=useState([0,0,0,0]);return <div className="corner-scene" role="group" aria-label="Interactive 3D shapes"><Boundary><Suspense fallback={null}><Canvas camera={{position:[0,0,8],fov:45}} dpr={[1,1.5]} frameloop={reduced?'demand':'always'}><ambientLight intensity={.85}/><directionalLight position={[-3,5,7]} intensity={2.1}/><Shapes reduced={reduced} ready={ready} turns={turns}/></Canvas></Suspense></Boundary>{["pyramid","diamond","cylinder","cube"].map((name,i)=><button key={name} className={`shape-control shape-${i}`} aria-label={`Rotate and recolor ${name}`} onClick={()=>setTurns(v=>v.map((n,j)=>j===i?n+1:n))}/>)}</div>}
